"""Generate Windows x64 bindings from the checked-in official raylib 5.5 API.

Run: python raylib/generate-bindings.py
Source: https://github.com/raysan5/raylib/blob/5.5/parser/output/raylib_api.json
The generated C# is compatible with Windows PowerShell 5.1 and PowerShell 7.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
api = json.loads((ROOT / "raylib-api-5.5.json").read_text(encoding="utf-8-sig"))
structs = {s["name"]: s for s in api["structs"]}
aliases = {a["name"]: a["type"] for a in api["aliases"]}
callbacks = {c["name"] for c in api["callbacks"]}
primitives = {
    "void": "void", "bool": "bool", "char": "sbyte", "unsigned char": "byte",
    "short": "short", "unsigned short": "ushort", "int": "int",
    "unsigned int": "uint", "long": "int",  # C long is 32-bit on Windows x64.
    "float": "float", "double": "double", "va_list": "IntPtr",
}


def ctype(t):
    if "*" in t:
        return "IntPtr"
    t = t.removeprefix("const ")
    if t in primitives:
        return primitives[t]
    assert t in structs or t in aliases or t in callbacks, t
    return t


def fieldname(name):
    return name[0].upper() + name[1:]


out = []
def emit(line=""):
    out.append(line)


emit('// Generated by generate-bindings.py. Do not edit; regenerate instead.')
emit('// raylib 5.5: all 581 raylib.h functions, structs, aliases, enums and callbacks.')
emit('// Native raylib license is in LICENSE.raylib. All native pointers retain C ownership semantics.')
emit('using System;\nusing System.Runtime.InteropServices;\nusing System.Text;')
emit('namespace RaylibPowerShell {')

for enum in api["enums"]:
    if enum["name"] in ("ConfigFlags", "Gesture"):
        emit('    [Flags]')
    emit('    public enum %s : int {' % enum["name"])
    for value in enum["values"]:
        emit('        %s = %s,' % (value["name"], value["value"]))
    emit('    }')

# Store inline arrays as contiguous individual fields, with an array-valued property.
# This keeps every struct blittable, including default-initialized structs and ref calls.
for name in list(structs) + list(aliases):
    source = structs[aliases.get(name, name)]
    emit('    [StructLayout(LayoutKind.Sequential)]')
    emit('    public struct %s {' % name)
    names = []
    for f in source["fields"]:
        member = fieldname(f["name"])
        names.append(member)
        array = re.fullmatch(r'(.+)\[(\d+)\]', f["type"])
        if array:
            element, count = array.groups()
            element = "byte" if element == "char" else ctype(element)
            count = int(count)
            for index in range(count):
                emit('        public %s %s%d;' % (element, member, index))
            emit('        public %s[] %s {' % (element, member))
            emit('            get { return new %s[] { %s }; }' % (element, ', '.join(member + str(i) for i in range(count))))
            emit('            set {')
            emit('                if (value == null || value.Length != %d) throw new ArgumentException("Expected %d elements.");' % (count, count))
            for index in range(count):
                emit('                %s%d = value[%d];' % (member, index, index))
            emit('            }\n        }')
        elif f["type"] == "bool":
            emit('        private byte native%s;' % member)
            emit('        public bool %s { get { return native%s != 0; } set { native%s = (byte)(value ? 1 : 0); } }' % (member, member, member))
        else:
            emit('        public %s %s;' % (ctype(f["type"]), member))
    if name in ('Vector2', 'Vector3', 'Vector4', 'Quaternion', 'Color', 'Rectangle'):
        args = ', '.join(ctype(f['type']) + ' @' + f['name'] for f in source['fields'])
        assignments = ' '.join(fieldname(f['name']) + ' = @' + f['name'] + ';' for f in source['fields'])
        emit('        public %s(%s) { %s }' % (name, args, assignments))
    if name in aliases:
        canonical = aliases[name]
        for dest, src in ((canonical, name), (name, canonical)):
            emit('        public static implicit operator %s(%s v) { return new %s { %s }; }' %
                 (dest, src, dest, ', '.join(n + ' = v.' + n for n in names)))
    emit('    }')

for cb in api['callbacks']:
    emit('    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]')
    if cb['returnType'] == 'bool':
        emit('    [return: MarshalAs(UnmanagedType.I1)]')
    # Callback strings stay native pointers: valid only during the callback.
    emit('    public delegate %s %s(%s);' % (ctype(cb['returnType']), cb['name'],
         ', '.join(ctype(p['type']) + ' @' + p['name'] for p in cb.get('params', []))))

emit('    public static class Colors {')
for d in api['defines']:
    if d['type'] == 'COLOR':
        values = re.search(r'\{([^}]+)\}', d['value']).group(1).strip()
        emit('        public static readonly Color %s = new Color(%s);' % (d['name'], values))
emit('    }')
emit('    public static class Constants {')
emit('        public const string RAYLIB_VERSION = "5.5";')
emit('        public const int RAYLIB_VERSION_MAJOR = 5, RAYLIB_VERSION_MINOR = 5, RAYLIB_VERSION_PATCH = 0;')
emit('        public const float PI = (float)Math.PI, DEG2RAD = PI / 180.0f, RAD2DEG = 180.0f / PI;')
enumvalues = {v['name']: e['name'] for e in api['enums'] for v in e['values']}
for key, enumname in enumvalues.items():
    emit('        public const int %s = (int)%s.%s;' % (key, enumname, key))
for d in api['defines']:
    if d['type'] == 'UNKNOWN' and isinstance(d['value'], str) and d['value'] in enumvalues:
        emit('        public const int %s = %s;' % (d['name'], d['value']))
emit('    }')

emit('    public static class Api {')
emit('''        public const string BindingVersion = "5.5-complete-v1";
        public const int FunctionCount = 581;
        private static IntPtr library;
        [DllImport("kernel32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
        private static extern IntPtr LoadLibraryExW(string path, IntPtr file, uint flags);
        [DllImport("kernel32.dll", CharSet=CharSet.Ansi, ExactSpelling=true)]
        private static extern IntPtr GetProcAddress(IntPtr module, string name);
        public static void Load(string path) {
            if (library != IntPtr.Zero) return;
            library = LoadLibraryExW(path, IntPtr.Zero, 8);
            if (library == IntPtr.Zero) throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "Cannot load raylib: " + path);
        }
        public static bool HasExport(string name) { return GetProcAddress(library, name) != IntPtr.Zero; }
        // Copy a borrowed or allocated UTF-8 string without freeing it.
        public static string Utf8(IntPtr pointer) {
            if (pointer == IntPtr.Zero) return null;
            int length = 0;
            while (Marshal.ReadByte(pointer, length) != 0) length++;
            byte[] data = new byte[length];
            Marshal.Copy(pointer, data, 0, length);
            return Encoding.UTF8.GetString(data);
        }
        [DllImport("raylib.dll", CallingConvention=CallingConvention.Cdecl, ExactSpelling=true)]
        public static extern void rlDrawRenderBatchActive();
''')


def param_decl(p, mode='raw', function=''):
    t, n = p['type'], p['name']
    if mode == 'pointer' and ('*' in t or t in callbacks):
        return 'IntPtr @' + n
    if mode == 'friendly_pointer' and (t == 'const char *' or t in callbacks):
        return 'IntPtr @' + n
    if t == 'const char *':
        return '[MarshalAs(UnmanagedType.LPUTF8Str)] string @' + n
    if t == 'bool':
        return '[MarshalAs(UnmanagedType.I1)] bool @' + n
    if mode in ('friendly', 'friendly_pointer'):
        # Borrowed mutable structs and scalar output arguments; never apply to frees
        # or APIs that retain pointers (e.g. SetAutomationEventList).
        if t in ('Image *', 'Camera *', 'Wave *', 'Mesh *', 'Material *', 'Model *', 'Texture2D *') and function != 'SetWindowIcons':
            return 'ref ' + ctype(t[:-2]) + ' @' + n
        if t in ('int *', 'unsigned int *') and n in ('dataSize', 'compDataSize', 'outputSize', 'frames', 'fileSize', 'colorCount', 'count', 'codepointSize', 'utf8Size', 'position', 'materialCount', 'animCount'):
            return 'ref ' + ctype(t[:-2]) + ' @' + n
        if function == 'CheckCollisionLines' and n == 'collisionPoint':
            return 'ref Vector2 @' + n
        if function == 'GenImageFontAtlas' and n == 'glyphRecs':
            return 'ref IntPtr @' + n
        # Arrays are borrowed only for the duration of this call.
        if t in ('const Vector2 *', 'const Vector3 *', 'const Matrix *', 'const float *', 'const int *', 'const GlyphInfo *'):
            return '[In] ' + ctype(t[6:-2]) + '[] @' + n
        # LoadMusicStreamFromMemory retains data for subsequent decoding: raw pointer only.
        if t == 'const unsigned char *' and function != 'LoadMusicStreamFromMemory':
            return '[In] byte[] @' + n
        if (function == 'SetWindowIcons' and n == 'images') or (function in ('ImageDrawTriangleFan', 'ImageDrawTriangleStrip') and n == 'points'):
            return '[In] ' + ctype(t[:-2]) + '[] @' + n
        if n == 'codepoints' and function in ('LoadFontEx', 'LoadFontFromMemory', 'LoadFontData'):
            return '[In] int[] @' + n
    return ctype(t) + ' @' + n


for fn in api['functions']:
    name = fn['name']
    params = fn.get('params', [])
    emit('        // ' + fn['description'])
    if name in ('TraceLog', 'TextFormat'):
        # Fixed-signature calls to the two C varargs exports. Always use %s so user
        # text cannot become an uncontrolled native format string.
        ret = ctype(fn['returnType'])
        prefix = 'int level, ' if name == 'TraceLog' else ''
        emit('        [DllImport("raylib.dll", EntryPoint="%s", CallingConvention=CallingConvention.Cdecl, ExactSpelling=true)]' % name)
        emit('        private static extern %s Native%s(%s[MarshalAs(UnmanagedType.LPUTF8Str)] string format, [MarshalAs(UnmanagedType.LPUTF8Str)] string text);' % (ret, name, prefix))
        emit('        public static %s %s(%sstring format, params object[] args) {' % (ret, name, prefix))
        emit('            string text = args == null || args.Length == 0 ? format : string.Format(System.Globalization.CultureInfo.InvariantCulture, format, args);')
        emit('            %sNative%s(%s"%%s", text);' % ('return ' if ret != 'void' else '', name, 'level, ' if name == 'TraceLog' else ''))
        emit('        }')
        continue
    emitted = set()
    for mode in ('raw', 'friendly', 'pointer', 'friendly_pointer'):
        signature = ', '.join(param_decl(p, mode, name) for p in params)
        if signature in emitted:
            continue
        emitted.add(signature)
        emit('        [DllImport("raylib.dll", CallingConvention=CallingConvention.Cdecl, ExactSpelling=true)]')
        if fn['returnType'] == 'bool':
            emit('        [return: MarshalAs(UnmanagedType.I1)]')
        emit('        public static extern %s %s(%s);' % (ctype(fn['returnType']), name, signature))
emit('    }')
emit('}')
(ROOT / 'Bindings.cs').write_text('\n'.join(out) + '\n', encoding='utf-8')
assert len(api['functions']) == 581
print('Generated all 581 functions, %d structs, %d aliases, %d enums, %d callbacks.' %
      (len(structs), len(aliases), len(api['enums']), len(callbacks)))
